version: '3'
services:
  server:
    build: .
    ports:
     - "8888:80"
    #  - "443:443"
    volumes:
     - .:/var/www
  # composer:
  #   image: composer
  #   volumes:
  #    - /Users/tim/ScoopM:/app


